# MyBatis
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: io.terminus.doctor.workflow.model

# Datasource
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/pig_doctor?useUnicode=true&characterEncoding=UTF8&autoReconnect=true
  username: root
  password: anywhere

# Dubbo
dubbo:
  name: doctor-workflow
  registry: zookeeper://127.0.0.1:2181
  port: -1
  timeout: 10000
  threads: 100
  heartBeats: 10000

# Redis
redis:
  host: 127.0.0.1
  port: 6379
  max-total: 10
  max-idle: 2
  test-on-borrow: true
