server:
  port: 8091

# MyBatis
mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: >
    io.terminus.doctor.warehouse.model,
    io.terminus.parana.(user|file|article|user.address).model,io.terminus.doctor.user.model,
    io.terminus.parana.msg.model,
    io.terminus.doctor.event.model,io.terminus.doctor.workflow.model,
    io.terminus.parana.config.model,
    io.terminus.doctor.basic.model,
    io.terminus.parana.msg.model,
    io.terminus.doctor.msg.model

# Datasource
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/pig_doctor?useUnicode=true&characterEncoding=UTF8
  username: root
  password: anywhere
# Dubbo
rpc.mode: false
rpc.dubbo:
    module: doctor-move-data
    registryAddress: 127.0.0.1:2181
    version: 1.0.0

logging:
  file: /var/log/doctor/event.log
  level.*: INFO

# zookeeper
zookeeper:
  host: 101.201.44.35
  port: 2181

# Redis
redis:
  host: 101.201.44.35
  port: 6379
  max-total: 10
  max-idle: 2
  test-on-borrow: true

# search
search:
  host: 127.0.0.1
  port: 9200

flow:
  definition:
    key:
      sow: sow
      boar: boar