server:
  port: 8091

# MyBatis
mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: >
    io.terminus.doctor.basic.model,
    io.terminus.parana.(user|file|article|user.address).model,io.terminus.doctor.user.model,
    io.terminus.parana.msg.model,
    io.terminus.doctor.event.model,
    io.terminus.parana.config.model,
    io.terminus.doctor.basic.model

# Datasource
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/pig_doctor_v4?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
  username: root
  password: anywhere
# Dubbo
rpc.mode: false
rpc.dubbo:
    module: doctor-move-data
    registryAddress: 127.0.0.1:2181
    version: 1.0.0

logging:
  file: /var/log/doctor/move-data.log
  level.*: INFO

# zookeeper
zookeeper:
  host: 101.201.44.35
  port: 2181
  zkTopic: pig.doctor.topic
  cacheTopic: pig.user.topic

# Redis
redis:
  host: 101.201.44.35
  port: 6379
  max-total: 10
  max-idle: 2
  test-on-borrow: true

# 用户中心的 zk topic，每个子系统保持一致
user.center.topic: user-center-topic

# 拥有所有权限的用户id
xrnm.auth.user.id: 10