# MyBatis
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: io.terminus.doctor.basic.model

# Datasource
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://101.201.44.35:3306/pig_doctor?useUnicode=true&characterEncoding=UTF8&autoReconnect=true
  username: root
  password: anywhere

# Dubbo
rpc.mode: true
rpc.dubbo:
    module: doctor-basic
    registryAddress: 101.201.44.35:2181
    version: 1.0.0

logging:
  file: /var/log/doctor/basic.log

# zookeeper
zookeeper:
  host: 101.201.44.35
  port: 2181

# Redis
redis:
  #host: 101.201.44.35
  host: 127.0.0.1
  port: 6379
  max-total: 10
  max-idle: 2
  test-on-borrow: true

# search
search:
  host: 127.0.0.1
  port: 9200