server:
  port: 8091
  context-path: /

# MyBatis
mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: >
    io.terminus.doctor.basic.model,
    io.terminus.parana.(user|file|article|user.address).model,io.terminus.doctor.user.model,
    io.terminus.parana.msg.model,
    io.terminus.doctor.event.model,
    io.terminus.parana.config.model,
    io.terminus.doctor.basic.model

# Datasource
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://rdsepg5mnd9c63a5a5bi.mysql.rds.aliyuncs.com:3306/pig_doctor?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
  username: xrnm
  password: anywhere
# Dubbo
rpc.mode: false
rpc.dubbo:
    module: doctor-move-data
    registryAddress: 127.0.0.1:2181
    version: 1.0.0
    check: false

logging:
  path: /var/log/doctor

# zookeeper
zookeeper:
  host: 127.0.0.1
  port: 2181
  zkTopic: pig.doctor.topic
  cacheTopic: pig.user.topic

# Redis
redis:
  host: 127.0.0.1
  port: 6379
  max-total: 10
  max-idle: 2
  test-on-borrow: true

# 用户中心的 zk topic，每个子系统保持一致
user.center.topic: user-center-topic

# 拥有所有权限的用户id
xrnm.auth.user.id: 10