server:
  context-path: /
  port: 8081

session:
  cookie-context-path: /
  cookie-domain: bbc.dev
  cookie-max-age: 1800
  cookie-name: msid
  source: redis
  serialize-type: json
  redis-host: 127.0.0.1
  redis-port: 8888
  redis-index: 1
  redis-cluster: false
  redis-test-on-borrow: true
  redis-max-total: 10
  redis-max-idle: 0
  redis-prefix: afsession
  mode: manager


dubbo:
  name: doctor-web
  registry: zookeeper://127.0.0.1:2181
  port: -1
  timeout: 10000
  threads: 100
  heartBeats: 10000
  mode: consumer

logging:
  file: /path/to/web.log
  level.*: INFO
  level.io.terminus: DEBUG

openplatform:
  mode: GATEWAY

parana:
  config:
    mode: server

zookeeper:
  host: 127.0.0.1
  port: 2181

spring:
  messages:
    basename: messages,op/messages,user/messages
    cache-seconds: -1
    encoding: UTF-8
    fallback-to-system-locale: true

oss:
  endpoint: todo
  appKey: todo
  appSecret: todo
  bucketName: terminus


image:
  base:
    url: http://terminus.oss-cn-hangzhou.aliyuncs.com
