server:
  context-path: /
  port: 8081

session:
  cookie-context-path: /
  cookie-domain: doctor.com
  cookie-max-age: 1800
  maxInactiveInterval: 259200
  cookie-name: msid
  source: redis
  serialize-type: json
  redis-host: 101.201.44.35
  redis-port: 6379
  redis-index: 1
  redis-cluster: false
  redis-test-on-borrow: true
  redis-max-total: 10
  redis-max-idle: 0
  redis-prefix: afsession

# Dubbo
rpc.mode: true
rpc.dubbo:
    module: doctor-open
    registryAddress: 101.201.44.35:2181
    version: 1.0.0

logging:
  file: /var/log/doctor/open.log
  level.*: INFO
  level.io.terminus: DEBUG

openplatform:
  mode: GATEWAY

parana:
  config:
    mode: server
  auth:
    level: easy
    path: /home/admin/assets/pidgey/
    key: MOBILE

zookeeper:
  host: 101.201.44.35
  port: 2181

#电商系统的 zookeeper 配置
zookeeper-pigmall:
  host: 101.201.44.35
  port: 2181
  cacheTopic: pigmall.cache.user.clear # pigmall 电商系统的 cacheTopic

spring:
  messages:
    basename: messages,op/messages,user/messages
    cache-seconds: -1
    encoding: UTF-8
    fallback-to-system-locale: true

oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  appKey: n67jFjUcEjZxPOZf
  appSecret: ZOPL1A33iQB52g60Dgvs3xT2FJqeaf
  bucketName: pigmall


image:
  base:
    url: http://pigmall.oss-cn-beijing.aliyuncs.com

msg:
  test.enabled: true
  gateway:
    version: simple
    sms: #包含的短信网关实现bean
      luoSiMaoSmsService:
    email: #包含的邮件网关实现bean
      commonEmailService:
    apppush: #包含的app消息推送实现bean
      umengAppPushServiceIos:
      umengAppPushServiceAndroid:
  current:
    smsService: luoSiMaoSmsService
    emailService: commonEmailService
    appPushService: umengAppPushService #当前的app消息推送网关服务
  webservice:
    version: db
    channel: #WEB层开启的消息服务, 在Controller中可以用@Qualifier("smsWebService")方式指明注入的MsgWebService
      sms:  #开启WEB层短信服务 SmsWebService, 使用时@Qualifier("smsWebService")
      email:  #开启WEB层邮件服务 EmailWebService, 使用时@Qualifier("emailWebService")
      notify:  #开启WEB层站内信服务 NotifyWebService, 使用时@Qualifier("notifyWebService")
      apppush:  #开启WEB层APP消息推送服务 AppPushWebService, 使用时@Qualifier("appPushWebService")
  luosimao:
    sendUrl: http://sms-api.luosimao.com/v1/http_get/send/json
    statusUrl: http://sms-api.luosimao.com/v1/http_get/status/json
    apiKey: 35dec4a658e7a3fe96af38a62540cacc
    companyName: 【新融农牧】
  email:
    host: smtp.mxhichina.com
    port: 25
    account: no-reply@xrnm.com
    password: 123456Pigmall
    protocol: 2
  umeng: #友盟APP消息推送网关配置
    android: #Android应用配置
      appKey: 574ced4267e58eef570035c7
      appSecret: jmaegca1mvlzpxewuufcn6kbxhebpzeo
    ios: #IOS应用配置
      appKey: 574cecdce0f55a85f00028fe
      appSecret: ws685rsevimn8fgx6mmxzzgx7bs1y9pn
