spring:
  profiles:
    include: zookeeper

# MyBatis
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: io.terminus.doctor.event.model,io.terminus.parana.msg.model

# Datasource
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://rdsepg5mnd9c63a5a5bi.mysql.rds.aliyuncs.com:3306/pig_doctor?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&allowMultiQueries=true
  username: xrnm
  password: anywhere
  connection-timeout: 5000

# Dubbo
rpc.mode: true
rpc.dubbo:
    module: doctor-event
    registryAddress: 127.0.0.1:2181
    version: 1.0.0
    check: false

logging:
  path: /var/log/doctor

# zookeeper
zookeeper:
  host: 127.0.0.1
  port: 2181
  zkTopic: pig.doctor.topic

# Redis
redis:
  host: 127.0.0.1
  port: 6379
  max-total: 10
  max-idle: 2
  test-on-borrow: true