# MyBatis
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: io.terminus.parana.(user|file|article|user.address).model,io.terminus.doctor.user.model

# Datasource
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://rdsepg5mnd9c63a5a5bi.mysql.rds.aliyuncs.com:3306/pig_doctor?useUnicode=true&characterEncoding=UTF8&autoReconnect=true
  username: xrnm
  password: anywhere
  connection-timeout: 5000

# Dubbo
rpc.mode: true
rpc.dubbo:
    module: doctor-user
    registryAddress: 127.0.0.1:2181
    version: 1.0.0
    check: false

logging:
  file: /var/log/doctor/user.log

# zookeeper
zookeeper:
  host: 127.0.0.1
  port: 2181
  cacheTopic: pig.user.topic

# 用户中心的 zk topic，每个子系统保持一致
user.center.topic: user-center-topic

# Redis
redis:
  host: 127.0.0.1
  port: 6379
  max-total: 10
  max-idle: 2
  test-on-borrow: true

doctor:
  url: https://doctor.xrnm.com