server:
  context-path: /
  port: 8082

pampas:
  rootPath: /home/admin/assets/pidgeotto
  apps:
    - key: PC
  devMode: false
  mvc:
    ignoreInterceptors:
      - Login
      - Auth
    customInterceptors:
      - doctorLoginInterceptor
      - doctorAuthInterceptor
  redis:
    host: 127.0.0.1
    port: 6379
  design:
    enable: false
  locale: zh_CN

session:
  cookie-context-path: /
  cookie-domain: doctor.com
  cookie-max-age: 1800
  cookie-name: msid
  source: redis
  serialize-type: json
  redis-host: 101.201.44.35
  redis-port: 6379
  redis-index: 1
  redis-cluster: false
  redis-test-on-borrow: true
  redis-max-total: 10
  redis-max-idle: 0
  redis-prefix: afsession

dubbo:
  name: doctor-admin
  registry: zookeeper://101.201.44.35:2181
  port: -1
  timeout: 10000
  threads: 100
  heartBeats: 10000
  mode: consumer

# zookeeper
zookeeper:
  host: 101.201.44.35
  port: 2181

logging:
  file: /var/log/doctor/admin.log
  level.*: DEBUG

image:
  base:
    url: http://img.xrnm.com

oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  appKey: n67jFjUcEjZxPOZf
  appSecret: ZOPL1A33iQB52g60Dgvs3xT2FJqeaf
  bucketName: pigmall
