# MyBatis
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: io.terminus.doctor.event.model,io.terminus.doctor.workflow.model

# Datasource
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://101.201.44.35:3306/pig_doctor?useUnicode=true&characterEncoding=UTF8&autoReconnect=true
  username: root
  password: anywhere

# Dubbo
dubbo:
  name: doctor-event
  registry: zookeeper://101.201.44.35:2181
  port: -1
  timeout: 10000
  threads: 100
  heartBeats: 10000

logging:
  file: /var/log/doctor/event.log
  level.*: INFO

# zookeeper
zookeeper:
  host: 101.201.44.35
  port: 2181
  cacheTopic: pig.event.topic

# Redis
redis:
  host: 101.201.44.35
  port: 6379
  max-total: 10
  max-idle: 2
  test-on-borrow: true

# search
search:
  host: 101.201.44.35
  port: 9200

search.pig:
  index-name: pigs
  index-type: pig
  mapping-path: search/pig_mapping.json
  full-dump-range: 3
  batch-size: 100

search.group:
  index-name: groups
  index-type: group
  mapping-path: search/group_mapping.json
  full-dump-range: 3
  batch-size: 100

search.barn:
  index-name: barns
  index-type: barn
  mapping-path: search/barn_mapping.json
  full-dump-range: 3
  batch-size: 100
